apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: smap
  labels:
    app: notification-api
type: Opaque
stringData:
  # Redis Configuration
  REDIS_HOST: "redis-client.infrastructure.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "21042004"

  # JWT Configuration
  JWT_SECRET_KEY: "smap-jwt-secret-2026-5cbPq8ZNywUafL3mX2r7HDqE1vS9kC4b0MRgx6VtYzQJKpLn"

  # Discord Webhook (Optional)
  DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1405400755300470835/i-GoIV82oqmI9Ts7dBW07LB3JB1fKSY8Di7Z6DkVnFlCSXJ389TTj3e7X0DTRIv6IXwN"
